# .mockery.yaml
quiet: false
with-expecter: true
issue-845-fix: true
resolve-type-alias: false
disable-version-string: true

packages:
  library-service/internal/domain/author:
    config:
      dir: "mocks"
      outpkg: "mocks"
    interfaces:
      Repository:
        config:
          filename: "AuthorRepository.go"
          mockname: "MockAuthorRepository"
      Cache:
        config:
          filename: "AuthorCache.go"
          mockname: "MockAuthorCache"

  library-service/internal/domain/book:
    config:
      dir: "mocks"
      outpkg: "mocks"
    interfaces:
      Repository:
        config:
          filename: "BookRepository.go"
          mockname: "MockBookRepository"
      Cache:
        config:
          filename: "BookCache.go"
          mockname: "MockBookCache"

  library-service/internal/domain/member:
    config:
      dir: "mocks"
      outpkg: "mocks"
    interfaces:
      Repository:
        config:
          filename: "MemberRepository.go"
          mockname: "MockMemberRepository"

  library-service/internal/service/interfaces:
    config:
      dir: "mocks"
      outpkg: "mocks"
    interfaces:
      BookService:
        config:
          filename: "BookService.go"
          mockname: "MockBookService"
      AuthorService:
        config:
          filename: "AuthorService.go"
          mockname: "MockAuthorService"
      MemberService:
        config:
          filename: "MemberService.go"
          mockname: "MockMemberService"
      AuthService:
        config:
          filename: "AuthService.go"
          mockname: "MockAuthService"

  library-service/internal/domain/user:
    config:
      dir: "mocks"
      outpkg: "mocks"
    interfaces:
      Repository:
        config:
          filename: "UserRepository.go"
          mockname: "MockUserRepository"