// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        string
	FullName  pgtype.Text
	Pseudonym pgtype.Text
	Specialty pgtype.Text
}
