// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	author "library-service/internal/domain/author"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthorCache is an autogenerated mock type for the Cache type
type MockAuthorCache struct {
	mock.Mock
}

type MockAuthorCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorCache) EXPECT() *MockAuthorCache_Expecter {
	return &MockAuthorCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAuthorCache) Get(ctx context.Context, id string) (author.Entity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 author.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (author.Entity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) author.Entity); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(author.Entity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAuthorCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthorCache_Expecter) Get(ctx interface{}, id interface{}) *MockAuthorCache_Get_Call {
	return &MockAuthorCache_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAuthorCache_Get_Call) Run(run func(ctx context.Context, id string)) *MockAuthorCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthorCache_Get_Call) Return(_a0 author.Entity, _a1 error) *MockAuthorCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorCache_Get_Call) RunAndReturn(run func(context.Context, string) (author.Entity, error)) *MockAuthorCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, id, entity
func (_m *MockAuthorCache) Set(ctx context.Context, id string, entity author.Entity) error {
	ret := _m.Called(ctx, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, author.Entity) error); ok {
		r0 = rf(ctx, id, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockAuthorCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - entity author.Entity
func (_e *MockAuthorCache_Expecter) Set(ctx interface{}, id interface{}, entity interface{}) *MockAuthorCache_Set_Call {
	return &MockAuthorCache_Set_Call{Call: _e.mock.On("Set", ctx, id, entity)}
}

func (_c *MockAuthorCache_Set_Call) Run(run func(ctx context.Context, id string, entity author.Entity)) *MockAuthorCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(author.Entity))
	})
	return _c
}

func (_c *MockAuthorCache_Set_Call) Return(_a0 error) *MockAuthorCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorCache_Set_Call) RunAndReturn(run func(context.Context, string, author.Entity) error) *MockAuthorCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorCache creates a new instance of MockAuthorCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorCache {
	mock := &MockAuthorCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
