// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	book "library-service/internal/domain/book"

	mock "github.com/stretchr/testify/mock"
)

// MockBookCache is an autogenerated mock type for the Cache type
type MockBookCache struct {
	mock.Mock
}

type MockBookCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookCache) EXPECT() *MockBookCache_Expecter {
	return &MockBookCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockBookCache) Get(ctx context.Context, id string) (book.Entity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 book.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (book.Entity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) book.Entity); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(book.Entity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBookCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookCache_Expecter) Get(ctx interface{}, id interface{}) *MockBookCache_Get_Call {
	return &MockBookCache_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockBookCache_Get_Call) Run(run func(ctx context.Context, id string)) *MockBookCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookCache_Get_Call) Return(_a0 book.Entity, _a1 error) *MockBookCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookCache_Get_Call) RunAndReturn(run func(context.Context, string) (book.Entity, error)) *MockBookCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, id, entity
func (_m *MockBookCache) Set(ctx context.Context, id string, entity book.Entity) error {
	ret := _m.Called(ctx, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, book.Entity) error); ok {
		r0 = rf(ctx, id, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockBookCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - entity book.Entity
func (_e *MockBookCache_Expecter) Set(ctx interface{}, id interface{}, entity interface{}) *MockBookCache_Set_Call {
	return &MockBookCache_Set_Call{Call: _e.mock.On("Set", ctx, id, entity)}
}

func (_c *MockBookCache_Set_Call) Run(run func(ctx context.Context, id string, entity book.Entity)) *MockBookCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(book.Entity))
	})
	return _c
}

func (_c *MockBookCache_Set_Call) Return(_a0 error) *MockBookCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookCache_Set_Call) RunAndReturn(run func(context.Context, string, book.Entity) error) *MockBookCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookCache creates a new instance of MockBookCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookCache {
	mock := &MockBookCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
