// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	author "library-service/internal/domain/author"
	book "library-service/internal/domain/book"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBookService is an autogenerated mock type for the BookService type
type MockBookService struct {
	mock.Mock
}

type MockBookService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookService) EXPECT() *MockBookService_Expecter {
	return &MockBookService_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function with given fields: ctx, req
func (_m *MockBookService) CreateBook(ctx context.Context, req book.Request) (book.Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 book.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, book.Request) (book.Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, book.Request) book.Response); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(book.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, book.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookService_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockBookService_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - req book.Request
func (_e *MockBookService_Expecter) CreateBook(ctx interface{}, req interface{}) *MockBookService_CreateBook_Call {
	return &MockBookService_CreateBook_Call{Call: _e.mock.On("CreateBook", ctx, req)}
}

func (_c *MockBookService_CreateBook_Call) Run(run func(ctx context.Context, req book.Request)) *MockBookService_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(book.Request))
	})
	return _c
}

func (_c *MockBookService_CreateBook_Call) Return(_a0 book.Response, _a1 error) *MockBookService_CreateBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookService_CreateBook_Call) RunAndReturn(run func(context.Context, book.Request) (book.Response, error)) *MockBookService_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBook provides a mock function with given fields: ctx, id
func (_m *MockBookService) DeleteBook(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookService_DeleteBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBook'
type MockBookService_DeleteBook_Call struct {
	*mock.Call
}

// DeleteBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookService_Expecter) DeleteBook(ctx interface{}, id interface{}) *MockBookService_DeleteBook_Call {
	return &MockBookService_DeleteBook_Call{Call: _e.mock.On("DeleteBook", ctx, id)}
}

func (_c *MockBookService_DeleteBook_Call) Run(run func(ctx context.Context, id string)) *MockBookService_DeleteBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookService_DeleteBook_Call) Return(_a0 error) *MockBookService_DeleteBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookService_DeleteBook_Call) RunAndReturn(run func(context.Context, string) error) *MockBookService_DeleteBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBook provides a mock function with given fields: ctx, id
func (_m *MockBookService) GetBook(ctx context.Context, id string) (book.Response, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 book.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (book.Response, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) book.Response); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(book.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookService_GetBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBook'
type MockBookService_GetBook_Call struct {
	*mock.Call
}

// GetBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookService_Expecter) GetBook(ctx interface{}, id interface{}) *MockBookService_GetBook_Call {
	return &MockBookService_GetBook_Call{Call: _e.mock.On("GetBook", ctx, id)}
}

func (_c *MockBookService_GetBook_Call) Run(run func(ctx context.Context, id string)) *MockBookService_GetBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookService_GetBook_Call) Return(_a0 book.Response, _a1 error) *MockBookService_GetBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookService_GetBook_Call) RunAndReturn(run func(context.Context, string) (book.Response, error)) *MockBookService_GetBook_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookAuthors provides a mock function with given fields: ctx, id
func (_m *MockBookService) ListBookAuthors(ctx context.Context, id string) ([]author.Response, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListBookAuthors")
	}

	var r0 []author.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]author.Response, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []author.Response); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]author.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookService_ListBookAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookAuthors'
type MockBookService_ListBookAuthors_Call struct {
	*mock.Call
}

// ListBookAuthors is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookService_Expecter) ListBookAuthors(ctx interface{}, id interface{}) *MockBookService_ListBookAuthors_Call {
	return &MockBookService_ListBookAuthors_Call{Call: _e.mock.On("ListBookAuthors", ctx, id)}
}

func (_c *MockBookService_ListBookAuthors_Call) Run(run func(ctx context.Context, id string)) *MockBookService_ListBookAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookService_ListBookAuthors_Call) Return(_a0 []author.Response, _a1 error) *MockBookService_ListBookAuthors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookService_ListBookAuthors_Call) RunAndReturn(run func(context.Context, string) ([]author.Response, error)) *MockBookService_ListBookAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// ListBooks provides a mock function with given fields: ctx
func (_m *MockBookService) ListBooks(ctx context.Context) ([]book.Response, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBooks")
	}

	var r0 []book.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]book.Response, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []book.Response); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookService_ListBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBooks'
type MockBookService_ListBooks_Call struct {
	*mock.Call
}

// ListBooks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBookService_Expecter) ListBooks(ctx interface{}) *MockBookService_ListBooks_Call {
	return &MockBookService_ListBooks_Call{Call: _e.mock.On("ListBooks", ctx)}
}

func (_c *MockBookService_ListBooks_Call) Run(run func(ctx context.Context)) *MockBookService_ListBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBookService_ListBooks_Call) Return(_a0 []book.Response, _a1 error) *MockBookService_ListBooks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookService_ListBooks_Call) RunAndReturn(run func(context.Context) ([]book.Response, error)) *MockBookService_ListBooks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function with given fields: ctx, id, req
func (_m *MockBookService) UpdateBook(ctx context.Context, id string, req book.Request) error {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, book.Request) error); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookService_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockBookService_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req book.Request
func (_e *MockBookService_Expecter) UpdateBook(ctx interface{}, id interface{}, req interface{}) *MockBookService_UpdateBook_Call {
	return &MockBookService_UpdateBook_Call{Call: _e.mock.On("UpdateBook", ctx, id, req)}
}

func (_c *MockBookService_UpdateBook_Call) Run(run func(ctx context.Context, id string, req book.Request)) *MockBookService_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(book.Request))
	})
	return _c
}

func (_c *MockBookService_UpdateBook_Call) Return(_a0 error) *MockBookService_UpdateBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookService_UpdateBook_Call) RunAndReturn(run func(context.Context, string, book.Request) error) *MockBookService_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookService creates a new instance of MockBookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookService {
	mock := &MockBookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
