// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	book "library-service/internal/domain/book"

	member "library-service/internal/domain/member"

	mock "github.com/stretchr/testify/mock"
)

// MockMemberService is an autogenerated mock type for the MemberService type
type MockMemberService struct {
	mock.Mock
}

type MockMemberService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberService) EXPECT() *MockMemberService_Expecter {
	return &MockMemberService_Expecter{mock: &_m.Mock}
}

// CreateMember provides a mock function with given fields: ctx, req
func (_m *MockMemberService) CreateMember(ctx context.Context, req member.Request) (member.Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMember")
	}

	var r0 member.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, member.Request) (member.Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, member.Request) member.Response); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(member.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, member.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberService_CreateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMember'
type MockMemberService_CreateMember_Call struct {
	*mock.Call
}

// CreateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - req member.Request
func (_e *MockMemberService_Expecter) CreateMember(ctx interface{}, req interface{}) *MockMemberService_CreateMember_Call {
	return &MockMemberService_CreateMember_Call{Call: _e.mock.On("CreateMember", ctx, req)}
}

func (_c *MockMemberService_CreateMember_Call) Run(run func(ctx context.Context, req member.Request)) *MockMemberService_CreateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(member.Request))
	})
	return _c
}

func (_c *MockMemberService_CreateMember_Call) Return(_a0 member.Response, _a1 error) *MockMemberService_CreateMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberService_CreateMember_Call) RunAndReturn(run func(context.Context, member.Request) (member.Response, error)) *MockMemberService_CreateMember_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMember provides a mock function with given fields: ctx, id
func (_m *MockMemberService) DeleteMember(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberService_DeleteMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMember'
type MockMemberService_DeleteMember_Call struct {
	*mock.Call
}

// DeleteMember is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMemberService_Expecter) DeleteMember(ctx interface{}, id interface{}) *MockMemberService_DeleteMember_Call {
	return &MockMemberService_DeleteMember_Call{Call: _e.mock.On("DeleteMember", ctx, id)}
}

func (_c *MockMemberService_DeleteMember_Call) Run(run func(ctx context.Context, id string)) *MockMemberService_DeleteMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberService_DeleteMember_Call) Return(_a0 error) *MockMemberService_DeleteMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberService_DeleteMember_Call) RunAndReturn(run func(context.Context, string) error) *MockMemberService_DeleteMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, id
func (_m *MockMemberService) GetMember(ctx context.Context, id string) (member.Response, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 member.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (member.Response, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) member.Response); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(member.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberService_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type MockMemberService_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMemberService_Expecter) GetMember(ctx interface{}, id interface{}) *MockMemberService_GetMember_Call {
	return &MockMemberService_GetMember_Call{Call: _e.mock.On("GetMember", ctx, id)}
}

func (_c *MockMemberService_GetMember_Call) Run(run func(ctx context.Context, id string)) *MockMemberService_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberService_GetMember_Call) Return(_a0 member.Response, _a1 error) *MockMemberService_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberService_GetMember_Call) RunAndReturn(run func(context.Context, string) (member.Response, error)) *MockMemberService_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// ListMemberBooks provides a mock function with given fields: ctx, memberID
func (_m *MockMemberService) ListMemberBooks(ctx context.Context, memberID string) ([]book.Response, error) {
	ret := _m.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for ListMemberBooks")
	}

	var r0 []book.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]book.Response, error)); ok {
		return rf(ctx, memberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []book.Response); ok {
		r0 = rf(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberService_ListMemberBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMemberBooks'
type MockMemberService_ListMemberBooks_Call struct {
	*mock.Call
}

// ListMemberBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockMemberService_Expecter) ListMemberBooks(ctx interface{}, memberID interface{}) *MockMemberService_ListMemberBooks_Call {
	return &MockMemberService_ListMemberBooks_Call{Call: _e.mock.On("ListMemberBooks", ctx, memberID)}
}

func (_c *MockMemberService_ListMemberBooks_Call) Run(run func(ctx context.Context, memberID string)) *MockMemberService_ListMemberBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberService_ListMemberBooks_Call) Return(_a0 []book.Response, _a1 error) *MockMemberService_ListMemberBooks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberService_ListMemberBooks_Call) RunAndReturn(run func(context.Context, string) ([]book.Response, error)) *MockMemberService_ListMemberBooks_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx
func (_m *MockMemberService) ListMembers(ctx context.Context) ([]member.Response, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []member.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]member.Response, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []member.Response); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]member.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberService_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockMemberService_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberService_Expecter) ListMembers(ctx interface{}) *MockMemberService_ListMembers_Call {
	return &MockMemberService_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx)}
}

func (_c *MockMemberService_ListMembers_Call) Run(run func(ctx context.Context)) *MockMemberService_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberService_ListMembers_Call) Return(_a0 []member.Response, _a1 error) *MockMemberService_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberService_ListMembers_Call) RunAndReturn(run func(context.Context) ([]member.Response, error)) *MockMemberService_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMember provides a mock function with given fields: ctx, id, req
func (_m *MockMemberService) UpdateMember(ctx context.Context, id string, req member.Request) error {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, member.Request) error); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberService_UpdateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMember'
type MockMemberService_UpdateMember_Call struct {
	*mock.Call
}

// UpdateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req member.Request
func (_e *MockMemberService_Expecter) UpdateMember(ctx interface{}, id interface{}, req interface{}) *MockMemberService_UpdateMember_Call {
	return &MockMemberService_UpdateMember_Call{Call: _e.mock.On("UpdateMember", ctx, id, req)}
}

func (_c *MockMemberService_UpdateMember_Call) Run(run func(ctx context.Context, id string, req member.Request)) *MockMemberService_UpdateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(member.Request))
	})
	return _c
}

func (_c *MockMemberService_UpdateMember_Call) Return(_a0 error) *MockMemberService_UpdateMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberService_UpdateMember_Call) RunAndReturn(run func(context.Context, string, member.Request) error) *MockMemberService_UpdateMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberService creates a new instance of MockMemberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberService {
	mock := &MockMemberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
