// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	member "library-service/internal/domain/member"

	mock "github.com/stretchr/testify/mock"
)

// MockMemberRepository is an autogenerated mock type for the Repository type
type MockMemberRepository struct {
	mock.Mock
}

type MockMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberRepository) EXPECT() *MockMemberRepository_Expecter {
	return &MockMemberRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, data
func (_m *MockMemberRepository) Add(ctx context.Context, data member.Entity) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, member.Entity) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, member.Entity) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, member.Entity) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockMemberRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - data member.Entity
func (_e *MockMemberRepository_Expecter) Add(ctx interface{}, data interface{}) *MockMemberRepository_Add_Call {
	return &MockMemberRepository_Add_Call{Call: _e.mock.On("Add", ctx, data)}
}

func (_c *MockMemberRepository_Add_Call) Run(run func(ctx context.Context, data member.Entity)) *MockMemberRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(member.Entity))
	})
	return _c
}

func (_c *MockMemberRepository_Add_Call) Return(_a0 string, _a1 error) *MockMemberRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_Add_Call) RunAndReturn(run func(context.Context, member.Entity) (string, error)) *MockMemberRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMemberRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMemberRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMemberRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMemberRepository_Delete_Call {
	return &MockMemberRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMemberRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockMemberRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_Delete_Call) Return(_a0 error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockMemberRepository) Get(ctx context.Context, id string) (member.Entity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 member.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (member.Entity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) member.Entity); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(member.Entity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMemberRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMemberRepository_Expecter) Get(ctx interface{}, id interface{}) *MockMemberRepository_Get_Call {
	return &MockMemberRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockMemberRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockMemberRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_Get_Call) Return(_a0 member.Entity, _a1 error) *MockMemberRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_Get_Call) RunAndReturn(run func(context.Context, string) (member.Entity, error)) *MockMemberRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockMemberRepository) List(ctx context.Context) ([]member.Entity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []member.Entity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]member.Entity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []member.Entity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]member.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMemberRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberRepository_Expecter) List(ctx interface{}) *MockMemberRepository_List_Call {
	return &MockMemberRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockMemberRepository_List_Call) Run(run func(ctx context.Context)) *MockMemberRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberRepository_List_Call) Return(_a0 []member.Entity, _a1 error) *MockMemberRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_List_Call) RunAndReturn(run func(context.Context) ([]member.Entity, error)) *MockMemberRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockMemberRepository) Update(ctx context.Context, id string, data member.Entity) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, member.Entity) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMemberRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data member.Entity
func (_e *MockMemberRepository_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockMemberRepository_Update_Call {
	return &MockMemberRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockMemberRepository_Update_Call) Run(run func(ctx context.Context, id string, data member.Entity)) *MockMemberRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(member.Entity))
	})
	return _c
}

func (_c *MockMemberRepository_Update_Call) Return(_a0 error) *MockMemberRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_Update_Call) RunAndReturn(run func(context.Context, string, member.Entity) error) *MockMemberRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberRepository creates a new instance of MockMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberRepository {
	mock := &MockMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
