// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package sqlc

import (
	"context"
)

const addBook = `-- name: AddBook :one
INSERT INTO books (name, genre, isbn, author_id) VALUES ($1, $2, $3, $4) returning id
`

type AddBookParams struct {
	Name     string
	Genre    string
	Isbn     string
	AuthorID string
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) (string, error) {
	row := q.db.QueryRow(ctx, addBook,
		arg.Name,
		arg.Genre,
		arg.Isbn,
		arg.AuthorID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, name, genre, isbn, author_id from books where id = $1
`

func (q *Queries) GetBook(ctx context.Context, id string) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Isbn,
		&i.AuthorID,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, name, genre, isbn, author_id FROM books ORDER BY id
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genre,
			&i.Isbn,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
set name = $2, genre = $3, isbn = $4, author_id = $5
where id = $1
`

type UpdateBookParams struct {
	ID       string
	Name     string
	Genre    string
	Isbn     string
	AuthorID string
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.Exec(ctx, updateBook,
		arg.ID,
		arg.Name,
		arg.Genre,
		arg.Isbn,
		arg.AuthorID,
	)
	return err
}
