// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package sqlc

import (
	"context"
)

const addMember = `-- name: AddMember :one
INSERT INTO members (id, full_name) VALUES ($1, $2) RETURNING id
`

type AddMemberParams struct {
	ID       string
	FullName string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (string, error) {
	row := q.db.QueryRow(ctx, addMember, arg.ID, arg.FullName)
	var id string
	err := row.Scan(&id)
	return id, err
}

const addMemberBook = `-- name: AddMemberBook :exec
INSERT INTO members_and_books (book_id, member_id) VALUES ($1, $2)
`

type AddMemberBookParams struct {
	BookID   string
	MemberID string
}

func (q *Queries) AddMemberBook(ctx context.Context, arg AddMemberBookParams) error {
	_, err := q.db.Exec(ctx, addMemberBook, arg.BookID, arg.MemberID)
	return err
}

const deleteAllMemberBooks = `-- name: DeleteAllMemberBooks :exec
DELETE FROM members_and_books WHERE member_id = $1
`

func (q *Queries) DeleteAllMemberBooks(ctx context.Context, memberID string) error {
	_, err := q.db.Exec(ctx, deleteAllMemberBooks, memberID)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const deleteMemberBook = `-- name: DeleteMemberBook :exec
DELETE FROM members_and_books WHERE book_id = $1 AND member_id = $2
`

type DeleteMemberBookParams struct {
	BookID   string
	MemberID string
}

func (q *Queries) DeleteMemberBook(ctx context.Context, arg DeleteMemberBookParams) error {
	_, err := q.db.Exec(ctx, deleteMemberBook, arg.BookID, arg.MemberID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, full_name FROM members WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(&i.ID, &i.FullName)
	return i, err
}

const getMemberBooks = `-- name: GetMemberBooks :many
SELECT book_id FROM members_and_books WHERE member_id = $1
`

func (q *Queries) GetMemberBooks(ctx context.Context, memberID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getMemberBooks, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var book_id string
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, full_name FROM members ORDER BY id
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.ID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET full_name = $2
WHERE id = $1
RETURNING id, full_name
`

type UpdateMemberParams struct {
	ID       string
	FullName string
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember, arg.ID, arg.FullName)
	var i Member
	err := row.Scan(&i.ID, &i.FullName)
	return i, err
}
