// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        string
	FullName  string
	Pseudonym string
	Specialty string
}

type Book struct {
	ID       string
	Name     string
	Genre    string
	Isbn     string
	AuthorID string
}

type Member struct {
	ID       string
	FullName string
}

type MembersAndBook struct {
	BookID   string
	MemberID string
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	FullName     pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
