// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Author struct {
	ID        string
	FullName  sql.NullString
	Pseudonym sql.NullString
	Specialty sql.NullString
}
