// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAuthor = `-- name: AddAuthor :one
INSERT INTO authors (full_name, pseudonym, specialty) VALUES ($1, $2, $3) RETURNING id
`

type AddAuthorParams struct {
	FullName  string
	Pseudonym string
	Specialty string
}

func (q *Queries) AddAuthor(ctx context.Context, arg AddAuthorParams) (string, error) {
	row := q.db.QueryRow(ctx, addAuthor, arg.FullName, arg.Pseudonym, arg.Specialty)
	var id string
	err := row.Scan(&id)
	return id, err
}

const addBook = `-- name: AddBook :one
INSERT INTO books (name, genre, isbn, author_id) VALUES ($1, $2, $3, $4) returning id
`

type AddBookParams struct {
	Name     string
	Genre    string
	Isbn     string
	AuthorID string
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) (string, error) {
	row := q.db.QueryRow(ctx, addBook,
		arg.Name,
		arg.Genre,
		arg.Isbn,
		arg.AuthorID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const addMember = `-- name: AddMember :one
INSERT INTO members (id, full_name) VALUES ($1, $2) RETURNING id
`

type AddMemberParams struct {
	ID       string
	FullName string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (string, error) {
	row := q.db.QueryRow(ctx, addMember, arg.ID, arg.FullName)
	var id string
	err := row.Scan(&id)
	return id, err
}

const addMemberBook = `-- name: AddMemberBook :exec
INSERT INTO members_and_books (book_id, member_id) VALUES ($1, $2)
`

type AddMemberBookParams struct {
	BookID   string
	MemberID string
}

func (q *Queries) AddMemberBook(ctx context.Context, arg AddMemberBookParams) error {
	_, err := q.db.Exec(ctx, addMemberBook, arg.BookID, arg.MemberID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, full_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	FullName     pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteAllMemberBooks = `-- name: DeleteAllMemberBooks :exec
DELETE FROM members_and_books WHERE member_id = $1
`

func (q *Queries) DeleteAllMemberBooks(ctx context.Context, memberID string) error {
	_, err := q.db.Exec(ctx, deleteAllMemberBooks, memberID)
	return err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const deleteMemberBook = `-- name: DeleteMemberBook :exec
DELETE FROM members_and_books WHERE book_id = $1 AND member_id = $2
`

type DeleteMemberBookParams struct {
	BookID   string
	MemberID string
}

func (q *Queries) DeleteMemberBook(ctx context.Context, arg DeleteMemberBookParams) error {
	_, err := q.db.Exec(ctx, deleteMemberBook, arg.BookID, arg.MemberID)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, full_name, pseudonym, specialty FROM authors WHERE id = $1
`

func (q *Queries) GetAuthor(ctx context.Context, id string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Pseudonym,
		&i.Specialty,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, name, genre, isbn, author_id from books where id = $1
`

func (q *Queries) GetBook(ctx context.Context, id string) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Isbn,
		&i.AuthorID,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, full_name FROM members WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(&i.ID, &i.FullName)
	return i, err
}

const getMemberBooks = `-- name: GetMemberBooks :many
SELECT book_id FROM members_and_books WHERE member_id = $1
`

func (q *Queries) GetMemberBooks(ctx context.Context, memberID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getMemberBooks, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var book_id string
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, full_name, pseudonym, specialty FROM authors ORDER BY id
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Pseudonym,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, name, genre, isbn, author_id FROM books ORDER BY id
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genre,
			&i.Isbn,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, full_name FROM members ORDER BY id
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.ID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET 
    full_name = $2,
    pseudonym = $3,
    specialty = $4
WHERE id = $1
RETURNING id, full_name, pseudonym, specialty
`

type UpdateAuthorParams struct {
	ID        string
	FullName  string
	Pseudonym string
	Specialty string
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, updateAuthor,
		arg.ID,
		arg.FullName,
		arg.Pseudonym,
		arg.Specialty,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Pseudonym,
		&i.Specialty,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
set name = $2, genre = $3, isbn = $4, author_id = $5
where id = $1
`

type UpdateBookParams struct {
	ID       string
	Name     string
	Genre    string
	Isbn     string
	AuthorID string
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.Exec(ctx, updateBook,
		arg.ID,
		arg.Name,
		arg.Genre,
		arg.Isbn,
		arg.AuthorID,
	)
	return err
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET full_name = $2
WHERE id = $1
RETURNING id, full_name
`

type UpdateMemberParams struct {
	ID       string
	FullName string
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember, arg.ID, arg.FullName)
	var i Member
	err := row.Scan(&i.ID, &i.FullName)
	return i, err
}
