// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addAuthor = `-- name: AddAuthor :one
INSERT INTO authors (full_name, pseudonym, specialty) VALUES ($1, $2, $3) RETURNING id
`

type AddAuthorParams struct {
	FullName  sql.NullString
	Pseudonym sql.NullString
	Specialty sql.NullString
}

func (q *Queries) AddAuthor(ctx context.Context, arg AddAuthorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addAuthor, arg.FullName, arg.Pseudonym, arg.Specialty)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteAuthor = `-- name: DeleteAuthor :one
DELETE FROM authors WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteAuthor(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteAuthor, id)
	err := row.Scan(&id)
	return id, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, full_name, pseudonym, specialty FROM authors WHERE id = $1
`

func (q *Queries) GetAuthor(ctx context.Context, id string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Pseudonym,
		&i.Specialty,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, full_name, pseudonym, specialty FROM authors ORDER BY id
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Pseudonym,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET 
    full_name = $2,
    pseudonym = $3,
    specialty = $4
WHERE id = $1
RETURNING id, full_name, pseudonym, specialty
`

type UpdateAuthorParams struct {
	ID        string
	FullName  sql.NullString
	Pseudonym sql.NullString
	Specialty sql.NullString
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, updateAuthor,
		arg.ID,
		arg.FullName,
		arg.Pseudonym,
		arg.Specialty,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Pseudonym,
		&i.Specialty,
	)
	return i, err
}
