// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "library-service/internal/domain/user"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// RefreshToken provides a mock function with given fields: ctx, req
func (_m *MockAuthService) RefreshToken(ctx context.Context, req user.RefreshRequest) (user.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 user.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.RefreshRequest) (user.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.RefreshRequest) user.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(user.AuthResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.RefreshRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req user.RefreshRequest
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, req interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, req user.RefreshRequest)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.RefreshRequest))
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(_a0 user.AuthResponse, _a1 error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(context.Context, user.RefreshRequest) (user.AuthResponse, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function with given fields: ctx, req
func (_m *MockAuthService) SignIn(ctx context.Context, req user.SignInRequest) (user.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 user.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.SignInRequest) (user.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.SignInRequest) user.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(user.AuthResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.SignInRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockAuthService_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - req user.SignInRequest
func (_e *MockAuthService_Expecter) SignIn(ctx interface{}, req interface{}) *MockAuthService_SignIn_Call {
	return &MockAuthService_SignIn_Call{Call: _e.mock.On("SignIn", ctx, req)}
}

func (_c *MockAuthService_SignIn_Call) Run(run func(ctx context.Context, req user.SignInRequest)) *MockAuthService_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.SignInRequest))
	})
	return _c
}

func (_c *MockAuthService_SignIn_Call) Return(_a0 user.AuthResponse, _a1 error) *MockAuthService_SignIn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_SignIn_Call) RunAndReturn(run func(context.Context, user.SignInRequest) (user.AuthResponse, error)) *MockAuthService_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function with given fields: ctx, req
func (_m *MockAuthService) SignUp(ctx context.Context, req user.SignUpRequest) (user.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 user.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.SignUpRequest) (user.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.SignUpRequest) user.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(user.AuthResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.SignUpRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockAuthService_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - req user.SignUpRequest
func (_e *MockAuthService_Expecter) SignUp(ctx interface{}, req interface{}) *MockAuthService_SignUp_Call {
	return &MockAuthService_SignUp_Call{Call: _e.mock.On("SignUp", ctx, req)}
}

func (_c *MockAuthService_SignUp_Call) Run(run func(ctx context.Context, req user.SignUpRequest)) *MockAuthService_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.SignUpRequest))
	})
	return _c
}

func (_c *MockAuthService_SignUp_Call) Return(_a0 user.AuthResponse, _a1 error) *MockAuthService_SignUp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_SignUp_Call) RunAndReturn(run func(context.Context, user.SignUpRequest) (user.AuthResponse, error)) *MockAuthService_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
