// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	author "library-service/internal/domain/author"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthorService is an autogenerated mock type for the AuthorService type
type MockAuthorService struct {
	mock.Mock
}

type MockAuthorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorService) EXPECT() *MockAuthorService_Expecter {
	return &MockAuthorService_Expecter{mock: &_m.Mock}
}

// AddAuthor provides a mock function with given fields: ctx, req
func (_m *MockAuthorService) AddAuthor(ctx context.Context, req author.Request) (author.Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddAuthor")
	}

	var r0 author.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, author.Request) (author.Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, author.Request) author.Response); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(author.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, author.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorService_AddAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAuthor'
type MockAuthorService_AddAuthor_Call struct {
	*mock.Call
}

// AddAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - req author.Request
func (_e *MockAuthorService_Expecter) AddAuthor(ctx interface{}, req interface{}) *MockAuthorService_AddAuthor_Call {
	return &MockAuthorService_AddAuthor_Call{Call: _e.mock.On("AddAuthor", ctx, req)}
}

func (_c *MockAuthorService_AddAuthor_Call) Run(run func(ctx context.Context, req author.Request)) *MockAuthorService_AddAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(author.Request))
	})
	return _c
}

func (_c *MockAuthorService_AddAuthor_Call) Return(_a0 author.Response, _a1 error) *MockAuthorService_AddAuthor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorService_AddAuthor_Call) RunAndReturn(run func(context.Context, author.Request) (author.Response, error)) *MockAuthorService_AddAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAuthor provides a mock function with given fields: ctx, id
func (_m *MockAuthorService) DeleteAuthor(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAuthor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorService_DeleteAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAuthor'
type MockAuthorService_DeleteAuthor_Call struct {
	*mock.Call
}

// DeleteAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthorService_Expecter) DeleteAuthor(ctx interface{}, id interface{}) *MockAuthorService_DeleteAuthor_Call {
	return &MockAuthorService_DeleteAuthor_Call{Call: _e.mock.On("DeleteAuthor", ctx, id)}
}

func (_c *MockAuthorService_DeleteAuthor_Call) Run(run func(ctx context.Context, id string)) *MockAuthorService_DeleteAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthorService_DeleteAuthor_Call) Return(_a0 error) *MockAuthorService_DeleteAuthor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorService_DeleteAuthor_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthorService_DeleteAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthor provides a mock function with given fields: ctx, id
func (_m *MockAuthorService) GetAuthor(ctx context.Context, id string) (author.Response, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthor")
	}

	var r0 author.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (author.Response, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) author.Response); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(author.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorService_GetAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthor'
type MockAuthorService_GetAuthor_Call struct {
	*mock.Call
}

// GetAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthorService_Expecter) GetAuthor(ctx interface{}, id interface{}) *MockAuthorService_GetAuthor_Call {
	return &MockAuthorService_GetAuthor_Call{Call: _e.mock.On("GetAuthor", ctx, id)}
}

func (_c *MockAuthorService_GetAuthor_Call) Run(run func(ctx context.Context, id string)) *MockAuthorService_GetAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthorService_GetAuthor_Call) Return(_a0 author.Response, _a1 error) *MockAuthorService_GetAuthor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorService_GetAuthor_Call) RunAndReturn(run func(context.Context, string) (author.Response, error)) *MockAuthorService_GetAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuthors provides a mock function with given fields: ctx
func (_m *MockAuthorService) ListAuthors(ctx context.Context) ([]author.Response, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAuthors")
	}

	var r0 []author.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]author.Response, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []author.Response); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]author.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorService_ListAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuthors'
type MockAuthorService_ListAuthors_Call struct {
	*mock.Call
}

// ListAuthors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthorService_Expecter) ListAuthors(ctx interface{}) *MockAuthorService_ListAuthors_Call {
	return &MockAuthorService_ListAuthors_Call{Call: _e.mock.On("ListAuthors", ctx)}
}

func (_c *MockAuthorService_ListAuthors_Call) Run(run func(ctx context.Context)) *MockAuthorService_ListAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuthorService_ListAuthors_Call) Return(_a0 []author.Response, _a1 error) *MockAuthorService_ListAuthors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorService_ListAuthors_Call) RunAndReturn(run func(context.Context) ([]author.Response, error)) *MockAuthorService_ListAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAuthor provides a mock function with given fields: ctx, id, req
func (_m *MockAuthorService) UpdateAuthor(ctx context.Context, id string, req author.Request) error {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, author.Request) error); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorService_UpdateAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAuthor'
type MockAuthorService_UpdateAuthor_Call struct {
	*mock.Call
}

// UpdateAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req author.Request
func (_e *MockAuthorService_Expecter) UpdateAuthor(ctx interface{}, id interface{}, req interface{}) *MockAuthorService_UpdateAuthor_Call {
	return &MockAuthorService_UpdateAuthor_Call{Call: _e.mock.On("UpdateAuthor", ctx, id, req)}
}

func (_c *MockAuthorService_UpdateAuthor_Call) Run(run func(ctx context.Context, id string, req author.Request)) *MockAuthorService_UpdateAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(author.Request))
	})
	return _c
}

func (_c *MockAuthorService_UpdateAuthor_Call) Return(_a0 error) *MockAuthorService_UpdateAuthor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorService_UpdateAuthor_Call) RunAndReturn(run func(context.Context, string, author.Request) error) *MockAuthorService_UpdateAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorService creates a new instance of MockAuthorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorService {
	mock := &MockAuthorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
