// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	author "library-service/internal/domain/author"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthorRepository is an autogenerated mock type for the Repository type
type MockAuthorRepository struct {
	mock.Mock
}

type MockAuthorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorRepository) EXPECT() *MockAuthorRepository_Expecter {
	return &MockAuthorRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, data
func (_m *MockAuthorRepository) Add(ctx context.Context, data author.Author) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, author.Author) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, author.Author) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, author.Author) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockAuthorRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - data author.Author
func (_e *MockAuthorRepository_Expecter) Add(ctx interface{}, data interface{}) *MockAuthorRepository_Add_Call {
	return &MockAuthorRepository_Add_Call{Call: _e.mock.On("Add", ctx, data)}
}

func (_c *MockAuthorRepository_Add_Call) Run(run func(ctx context.Context, data author.Author)) *MockAuthorRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(author.Author))
	})
	return _c
}

func (_c *MockAuthorRepository_Add_Call) Return(_a0 string, _a1 error) *MockAuthorRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorRepository_Add_Call) RunAndReturn(run func(context.Context, author.Author) (string, error)) *MockAuthorRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAuthorRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAuthorRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthorRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAuthorRepository_Delete_Call {
	return &MockAuthorRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAuthorRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAuthorRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthorRepository_Delete_Call) Return(_a0 error) *MockAuthorRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthorRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAuthorRepository) Get(ctx context.Context, id string) (author.Author, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 author.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (author.Author, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) author.Author); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(author.Author)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAuthorRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthorRepository_Expecter) Get(ctx interface{}, id interface{}) *MockAuthorRepository_Get_Call {
	return &MockAuthorRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAuthorRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockAuthorRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthorRepository_Get_Call) Return(_a0 author.Author, _a1 error) *MockAuthorRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorRepository_Get_Call) RunAndReturn(run func(context.Context, string) (author.Author, error)) *MockAuthorRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockAuthorRepository) List(ctx context.Context) ([]author.Author, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []author.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]author.Author, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []author.Author); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]author.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuthorRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthorRepository_Expecter) List(ctx interface{}) *MockAuthorRepository_List_Call {
	return &MockAuthorRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockAuthorRepository_List_Call) Run(run func(ctx context.Context)) *MockAuthorRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuthorRepository_List_Call) Return(_a0 []author.Author, _a1 error) *MockAuthorRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorRepository_List_Call) RunAndReturn(run func(context.Context) ([]author.Author, error)) *MockAuthorRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockAuthorRepository) Update(ctx context.Context, id string, data author.Author) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, author.Author) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthorRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAuthorRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data author.Author
func (_e *MockAuthorRepository_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockAuthorRepository_Update_Call {
	return &MockAuthorRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockAuthorRepository_Update_Call) Run(run func(ctx context.Context, id string, data author.Author)) *MockAuthorRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(author.Author))
	})
	return _c
}

func (_c *MockAuthorRepository_Update_Call) Return(_a0 error) *MockAuthorRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthorRepository_Update_Call) RunAndReturn(run func(context.Context, string, author.Author) error) *MockAuthorRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorRepository creates a new instance of MockAuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorRepository {
	mock := &MockAuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
