// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	book "library-service/internal/domain/book"

	mock "github.com/stretchr/testify/mock"
)

// MockBookRepository is an autogenerated mock type for the Repository type
type MockBookRepository struct {
	mock.Mock
}

type MockBookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookRepository) EXPECT() *MockBookRepository_Expecter {
	return &MockBookRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, data
func (_m *MockBookRepository) Add(ctx context.Context, data book.Book) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, book.Book) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, book.Book) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, book.Book) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockBookRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - data book.Book
func (_e *MockBookRepository_Expecter) Add(ctx interface{}, data interface{}) *MockBookRepository_Add_Call {
	return &MockBookRepository_Add_Call{Call: _e.mock.On("Add", ctx, data)}
}

func (_c *MockBookRepository_Add_Call) Run(run func(ctx context.Context, data book.Book)) *MockBookRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(book.Book))
	})
	return _c
}

func (_c *MockBookRepository_Add_Call) Return(_a0 string, _a1 error) *MockBookRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookRepository_Add_Call) RunAndReturn(run func(context.Context, book.Book) (string, error)) *MockBookRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBookRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBookRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockBookRepository_Delete_Call {
	return &MockBookRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBookRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockBookRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookRepository_Delete_Call) Return(_a0 error) *MockBookRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockBookRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockBookRepository) Get(ctx context.Context, id string) (book.Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (book.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) book.Book); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(book.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBookRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookRepository_Expecter) Get(ctx interface{}, id interface{}) *MockBookRepository_Get_Call {
	return &MockBookRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockBookRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockBookRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookRepository_Get_Call) Return(_a0 book.Book, _a1 error) *MockBookRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookRepository_Get_Call) RunAndReturn(run func(context.Context, string) (book.Book, error)) *MockBookRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockBookRepository) List(ctx context.Context) ([]book.Book, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]book.Book, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []book.Book); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBookRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBookRepository_Expecter) List(ctx interface{}) *MockBookRepository_List_Call {
	return &MockBookRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockBookRepository_List_Call) Run(run func(ctx context.Context)) *MockBookRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBookRepository_List_Call) Return(_a0 []book.Book, _a1 error) *MockBookRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookRepository_List_Call) RunAndReturn(run func(context.Context) ([]book.Book, error)) *MockBookRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockBookRepository) Update(ctx context.Context, id string, data book.Book) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, book.Book) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBookRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data book.Book
func (_e *MockBookRepository_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockBookRepository_Update_Call {
	return &MockBookRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockBookRepository_Update_Call) Run(run func(ctx context.Context, id string, data book.Book)) *MockBookRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(book.Book))
	})
	return _c
}

func (_c *MockBookRepository_Update_Call) Return(_a0 error) *MockBookRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookRepository_Update_Call) RunAndReturn(run func(context.Context, string, book.Book) error) *MockBookRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookRepository creates a new instance of MockBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookRepository {
	mock := &MockBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
