// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	book "library-service/internal/domain/book"

	mock "github.com/stretchr/testify/mock"
)

// MockCache is an autogenerated mocks type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Get provides a mocks function with given fields: ctx, id
func (_m *MockCache) Get(ctx context.Context, id string) (book.Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (book.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) book.Book); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(book.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_Get_Call is a *mocks.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mocks.On call
//   - ctx context.Context
//   - id string
func (_e *MockCache_Expecter) Get(ctx interface{}, id interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockCache_Get_Call) Run(run func(ctx context.Context, id string)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(_a0 book.Book, _a1 error) *MockCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(context.Context, string) (book.Book, error)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mocks function with given fields: ctx, id, entity
func (_m *MockCache) Set(ctx context.Context, id string, entity book.Book) error {
	ret := _m.Called(ctx, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, book.Book) error); ok {
		r0 = rf(ctx, id, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_Set_Call is a *mocks.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mocks.On call
//   - ctx context.Context
//   - id string
//   - entity book.Book
func (_e *MockCache_Expecter) Set(ctx interface{}, id interface{}, entity interface{}) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", ctx, id, entity)}
}

func (_c *MockCache_Set_Call) Run(run func(ctx context.Context, id string, entity book.Book)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(book.Book))
	})
	return _c
}

func (_c *MockCache_Set_Call) Return(_a0 error) *MockCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(context.Context, string, book.Book) error) *MockCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mocks and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
