// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	member "library-service/internal/domain/member"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockMemberRepository is an autogenerated mock type for the Repository type
type MockMemberRepository struct {
	mock.Mock
}

type MockMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberRepository) EXPECT() *MockMemberRepository_Expecter {
	return &MockMemberRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, data
func (_m *MockMemberRepository) Add(ctx context.Context, data member.Member) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, member.Member) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, member.Member) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, member.Member) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockMemberRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - data member.Member
func (_e *MockMemberRepository_Expecter) Add(ctx interface{}, data interface{}) *MockMemberRepository_Add_Call {
	return &MockMemberRepository_Add_Call{Call: _e.mock.On("Add", ctx, data)}
}

func (_c *MockMemberRepository_Add_Call) Run(run func(ctx context.Context, data member.Member)) *MockMemberRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(member.Member))
	})
	return _c
}

func (_c *MockMemberRepository_Add_Call) Return(_a0 string, _a1 error) *MockMemberRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_Add_Call) RunAndReturn(run func(context.Context, member.Member) (string, error)) *MockMemberRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMemberRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMemberRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMemberRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMemberRepository_Delete_Call {
	return &MockMemberRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMemberRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockMemberRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_Delete_Call) Return(_a0 error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// EmailExists provides a mock function with given fields: ctx, email
func (_m *MockMemberRepository) EmailExists(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for EmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_EmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailExists'
type MockMemberRepository_EmailExists_Call struct {
	*mock.Call
}

// EmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockMemberRepository_Expecter) EmailExists(ctx interface{}, email interface{}) *MockMemberRepository_EmailExists_Call {
	return &MockMemberRepository_EmailExists_Call{Call: _e.mock.On("EmailExists", ctx, email)}
}

func (_c *MockMemberRepository_EmailExists_Call) Run(run func(ctx context.Context, email string)) *MockMemberRepository_EmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_EmailExists_Call) Return(_a0 bool, _a1 error) *MockMemberRepository_EmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_EmailExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockMemberRepository_EmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockMemberRepository) Get(ctx context.Context, id string) (member.Member, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 member.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (member.Member, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) member.Member); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(member.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMemberRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMemberRepository_Expecter) Get(ctx interface{}, id interface{}) *MockMemberRepository_Get_Call {
	return &MockMemberRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockMemberRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockMemberRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_Get_Call) Return(_a0 member.Member, _a1 error) *MockMemberRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_Get_Call) RunAndReturn(run func(context.Context, string) (member.Member, error)) *MockMemberRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockMemberRepository) GetByEmail(ctx context.Context, email string) (member.Member, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 member.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (member.Member, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) member.Member); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(member.Member)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockMemberRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockMemberRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockMemberRepository_GetByEmail_Call {
	return &MockMemberRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockMemberRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockMemberRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_GetByEmail_Call) Return(_a0 member.Member, _a1 error) *MockMemberRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (member.Member, error)) *MockMemberRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockMemberRepository) List(ctx context.Context) ([]member.Member, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []member.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]member.Member, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []member.Member); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]member.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMemberRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMemberRepository_Expecter) List(ctx interface{}) *MockMemberRepository_List_Call {
	return &MockMemberRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockMemberRepository_List_Call) Run(run func(ctx context.Context)) *MockMemberRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMemberRepository_List_Call) Return(_a0 []member.Member, _a1 error) *MockMemberRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_List_Call) RunAndReturn(run func(context.Context) ([]member.Member, error)) *MockMemberRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockMemberRepository) Update(ctx context.Context, id string, data member.Member) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, member.Member) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMemberRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data member.Member
func (_e *MockMemberRepository_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockMemberRepository_Update_Call {
	return &MockMemberRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockMemberRepository_Update_Call) Run(run func(ctx context.Context, id string, data member.Member)) *MockMemberRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(member.Member))
	})
	return _c
}

func (_c *MockMemberRepository_Update_Call) Return(_a0 error) *MockMemberRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_Update_Call) RunAndReturn(run func(context.Context, string, member.Member) error) *MockMemberRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastLogin provides a mock function with given fields: ctx, id, loginTime
func (_m *MockMemberRepository) UpdateLastLogin(ctx context.Context, id string, loginTime time.Time) error {
	ret := _m.Called(ctx, id, loginTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, id, loginTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_UpdateLastLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastLogin'
type MockMemberRepository_UpdateLastLogin_Call struct {
	*mock.Call
}

// UpdateLastLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - loginTime time.Time
func (_e *MockMemberRepository_Expecter) UpdateLastLogin(ctx interface{}, id interface{}, loginTime interface{}) *MockMemberRepository_UpdateLastLogin_Call {
	return &MockMemberRepository_UpdateLastLogin_Call{Call: _e.mock.On("UpdateLastLogin", ctx, id, loginTime)}
}

func (_c *MockMemberRepository_UpdateLastLogin_Call) Run(run func(ctx context.Context, id string, loginTime time.Time)) *MockMemberRepository_UpdateLastLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockMemberRepository_UpdateLastLogin_Call) Return(_a0 error) *MockMemberRepository_UpdateLastLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_UpdateLastLogin_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockMemberRepository_UpdateLastLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberRepository creates a new instance of MockMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberRepository {
	mock := &MockMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
