// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	reservation "library-service/internal/domain/reservation"

	mock "github.com/stretchr/testify/mock"
)

// MockReservationRepository is an autogenerated mock type for the Repository type
type MockReservationRepository struct {
	mock.Mock
}

type MockReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationRepository) EXPECT() *MockReservationRepository_Expecter {
	return &MockReservationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockReservationRepository) Create(ctx context.Context, _a1 reservation.Reservation) (string, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, reservation.Reservation) (string, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, reservation.Reservation) string); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, reservation.Reservation) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReservationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 reservation.Reservation
func (_e *MockReservationRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockReservationRepository_Create_Call {
	return &MockReservationRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockReservationRepository_Create_Call) Run(run func(ctx context.Context, _a1 reservation.Reservation)) *MockReservationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reservation.Reservation))
	})
	return _c
}

func (_c *MockReservationRepository_Create_Call) Return(_a0 string, _a1 error) *MockReservationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_Create_Call) RunAndReturn(run func(context.Context, reservation.Reservation) (string, error)) *MockReservationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockReservationRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReservationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockReservationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockReservationRepository_Delete_Call {
	return &MockReservationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockReservationRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockReservationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReservationRepository_Delete_Call) Return(_a0 error) *MockReservationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockReservationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByMemberAndBook provides a mock function with given fields: ctx, memberID, bookID
func (_m *MockReservationRepository) GetActiveByMemberAndBook(ctx context.Context, memberID string, bookID string) ([]reservation.Reservation, error) {
	ret := _m.Called(ctx, memberID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByMemberAndBook")
	}

	var r0 []reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]reservation.Reservation, error)); ok {
		return rf(ctx, memberID, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []reservation.Reservation); ok {
		r0 = rf(ctx, memberID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, memberID, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_GetActiveByMemberAndBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByMemberAndBook'
type MockReservationRepository_GetActiveByMemberAndBook_Call struct {
	*mock.Call
}

// GetActiveByMemberAndBook is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
//   - bookID string
func (_e *MockReservationRepository_Expecter) GetActiveByMemberAndBook(ctx interface{}, memberID interface{}, bookID interface{}) *MockReservationRepository_GetActiveByMemberAndBook_Call {
	return &MockReservationRepository_GetActiveByMemberAndBook_Call{Call: _e.mock.On("GetActiveByMemberAndBook", ctx, memberID, bookID)}
}

func (_c *MockReservationRepository_GetActiveByMemberAndBook_Call) Run(run func(ctx context.Context, memberID string, bookID string)) *MockReservationRepository_GetActiveByMemberAndBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockReservationRepository_GetActiveByMemberAndBook_Call) Return(_a0 []reservation.Reservation, _a1 error) *MockReservationRepository_GetActiveByMemberAndBook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_GetActiveByMemberAndBook_Call) RunAndReturn(run func(context.Context, string, string) ([]reservation.Reservation, error)) *MockReservationRepository_GetActiveByMemberAndBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetByBookID provides a mock function with given fields: ctx, bookID
func (_m *MockReservationRepository) GetByBookID(ctx context.Context, bookID string) ([]reservation.Reservation, error) {
	ret := _m.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBookID")
	}

	var r0 []reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]reservation.Reservation, error)); ok {
		return rf(ctx, bookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []reservation.Reservation); ok {
		r0 = rf(ctx, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_GetByBookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBookID'
type MockReservationRepository_GetByBookID_Call struct {
	*mock.Call
}

// GetByBookID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
func (_e *MockReservationRepository_Expecter) GetByBookID(ctx interface{}, bookID interface{}) *MockReservationRepository_GetByBookID_Call {
	return &MockReservationRepository_GetByBookID_Call{Call: _e.mock.On("GetByBookID", ctx, bookID)}
}

func (_c *MockReservationRepository_GetByBookID_Call) Run(run func(ctx context.Context, bookID string)) *MockReservationRepository_GetByBookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReservationRepository_GetByBookID_Call) Return(_a0 []reservation.Reservation, _a1 error) *MockReservationRepository_GetByBookID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_GetByBookID_Call) RunAndReturn(run func(context.Context, string) ([]reservation.Reservation, error)) *MockReservationRepository_GetByBookID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockReservationRepository) GetByID(ctx context.Context, id string) (reservation.Reservation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (reservation.Reservation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) reservation.Reservation); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(reservation.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockReservationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockReservationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockReservationRepository_GetByID_Call {
	return &MockReservationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockReservationRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockReservationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReservationRepository_GetByID_Call) Return(_a0 reservation.Reservation, _a1 error) *MockReservationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (reservation.Reservation, error)) *MockReservationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMemberID provides a mock function with given fields: ctx, memberID
func (_m *MockReservationRepository) GetByMemberID(ctx context.Context, memberID string) ([]reservation.Reservation, error) {
	ret := _m.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for GetByMemberID")
	}

	var r0 []reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]reservation.Reservation, error)); ok {
		return rf(ctx, memberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []reservation.Reservation); ok {
		r0 = rf(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_GetByMemberID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMemberID'
type MockReservationRepository_GetByMemberID_Call struct {
	*mock.Call
}

// GetByMemberID is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockReservationRepository_Expecter) GetByMemberID(ctx interface{}, memberID interface{}) *MockReservationRepository_GetByMemberID_Call {
	return &MockReservationRepository_GetByMemberID_Call{Call: _e.mock.On("GetByMemberID", ctx, memberID)}
}

func (_c *MockReservationRepository_GetByMemberID_Call) Run(run func(ctx context.Context, memberID string)) *MockReservationRepository_GetByMemberID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReservationRepository_GetByMemberID_Call) Return(_a0 []reservation.Reservation, _a1 error) *MockReservationRepository_GetByMemberID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_GetByMemberID_Call) RunAndReturn(run func(context.Context, string) ([]reservation.Reservation, error)) *MockReservationRepository_GetByMemberID_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpired provides a mock function with given fields: ctx
func (_m *MockReservationRepository) ListExpired(ctx context.Context) ([]reservation.Reservation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListExpired")
	}

	var r0 []reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]reservation.Reservation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []reservation.Reservation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_ListExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpired'
type MockReservationRepository_ListExpired_Call struct {
	*mock.Call
}

// ListExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationRepository_Expecter) ListExpired(ctx interface{}) *MockReservationRepository_ListExpired_Call {
	return &MockReservationRepository_ListExpired_Call{Call: _e.mock.On("ListExpired", ctx)}
}

func (_c *MockReservationRepository_ListExpired_Call) Run(run func(ctx context.Context)) *MockReservationRepository_ListExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReservationRepository_ListExpired_Call) Return(_a0 []reservation.Reservation, _a1 error) *MockReservationRepository_ListExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_ListExpired_Call) RunAndReturn(run func(context.Context) ([]reservation.Reservation, error)) *MockReservationRepository_ListExpired_Call {
	_c.Call.Return(run)
	return _c
}

// ListPending provides a mock function with given fields: ctx
func (_m *MockReservationRepository) ListPending(ctx context.Context) ([]reservation.Reservation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPending")
	}

	var r0 []reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]reservation.Reservation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []reservation.Reservation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_ListPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPending'
type MockReservationRepository_ListPending_Call struct {
	*mock.Call
}

// ListPending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservationRepository_Expecter) ListPending(ctx interface{}) *MockReservationRepository_ListPending_Call {
	return &MockReservationRepository_ListPending_Call{Call: _e.mock.On("ListPending", ctx)}
}

func (_c *MockReservationRepository_ListPending_Call) Run(run func(ctx context.Context)) *MockReservationRepository_ListPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReservationRepository_ListPending_Call) Return(_a0 []reservation.Reservation, _a1 error) *MockReservationRepository_ListPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_ListPending_Call) RunAndReturn(run func(context.Context) ([]reservation.Reservation, error)) *MockReservationRepository_ListPending_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockReservationRepository) Update(ctx context.Context, _a1 reservation.Reservation) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, reservation.Reservation) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReservationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 reservation.Reservation
func (_e *MockReservationRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockReservationRepository_Update_Call {
	return &MockReservationRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockReservationRepository_Update_Call) Run(run func(ctx context.Context, _a1 reservation.Reservation)) *MockReservationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(reservation.Reservation))
	})
	return _c
}

func (_c *MockReservationRepository_Update_Call) Return(_a0 error) *MockReservationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_Update_Call) RunAndReturn(run func(context.Context, reservation.Reservation) error) *MockReservationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReservationRepository creates a new instance of MockReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationRepository {
	mock := &MockReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
