// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	payment "library-service/internal/domain/payment"

	mock "github.com/stretchr/testify/mock"
)

// MockSavedCardRepository is an autogenerated mock type for the SavedCardRepository type
type MockSavedCardRepository struct {
	mock.Mock
}

type MockSavedCardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSavedCardRepository) EXPECT() *MockSavedCardRepository_Expecter {
	return &MockSavedCardRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, card
func (_m *MockSavedCardRepository) Create(ctx context.Context, card payment.SavedCard) (string, error) {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, payment.SavedCard) (string, error)); ok {
		return rf(ctx, card)
	}
	if rf, ok := ret.Get(0).(func(context.Context, payment.SavedCard) string); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, payment.SavedCard) error); ok {
		r1 = rf(ctx, card)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSavedCardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSavedCardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - card payment.SavedCard
func (_e *MockSavedCardRepository_Expecter) Create(ctx interface{}, card interface{}) *MockSavedCardRepository_Create_Call {
	return &MockSavedCardRepository_Create_Call{Call: _e.mock.On("Create", ctx, card)}
}

func (_c *MockSavedCardRepository_Create_Call) Run(run func(ctx context.Context, card payment.SavedCard)) *MockSavedCardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(payment.SavedCard))
	})
	return _c
}

func (_c *MockSavedCardRepository_Create_Call) Return(_a0 string, _a1 error) *MockSavedCardRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSavedCardRepository_Create_Call) RunAndReturn(run func(context.Context, payment.SavedCard) (string, error)) *MockSavedCardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockSavedCardRepository) Deactivate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSavedCardRepository_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockSavedCardRepository_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSavedCardRepository_Expecter) Deactivate(ctx interface{}, id interface{}) *MockSavedCardRepository_Deactivate_Call {
	return &MockSavedCardRepository_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockSavedCardRepository_Deactivate_Call) Run(run func(ctx context.Context, id string)) *MockSavedCardRepository_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSavedCardRepository_Deactivate_Call) Return(_a0 error) *MockSavedCardRepository_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSavedCardRepository_Deactivate_Call) RunAndReturn(run func(context.Context, string) error) *MockSavedCardRepository_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSavedCardRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSavedCardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSavedCardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSavedCardRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSavedCardRepository_Delete_Call {
	return &MockSavedCardRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSavedCardRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSavedCardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSavedCardRepository_Delete_Call) Return(_a0 error) *MockSavedCardRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSavedCardRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSavedCardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCardToken provides a mock function with given fields: ctx, cardToken
func (_m *MockSavedCardRepository) GetByCardToken(ctx context.Context, cardToken string) (payment.SavedCard, error) {
	ret := _m.Called(ctx, cardToken)

	if len(ret) == 0 {
		panic("no return value specified for GetByCardToken")
	}

	var r0 payment.SavedCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (payment.SavedCard, error)); ok {
		return rf(ctx, cardToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) payment.SavedCard); ok {
		r0 = rf(ctx, cardToken)
	} else {
		r0 = ret.Get(0).(payment.SavedCard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cardToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSavedCardRepository_GetByCardToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCardToken'
type MockSavedCardRepository_GetByCardToken_Call struct {
	*mock.Call
}

// GetByCardToken is a helper method to define mock.On call
//   - ctx context.Context
//   - cardToken string
func (_e *MockSavedCardRepository_Expecter) GetByCardToken(ctx interface{}, cardToken interface{}) *MockSavedCardRepository_GetByCardToken_Call {
	return &MockSavedCardRepository_GetByCardToken_Call{Call: _e.mock.On("GetByCardToken", ctx, cardToken)}
}

func (_c *MockSavedCardRepository_GetByCardToken_Call) Run(run func(ctx context.Context, cardToken string)) *MockSavedCardRepository_GetByCardToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSavedCardRepository_GetByCardToken_Call) Return(_a0 payment.SavedCard, _a1 error) *MockSavedCardRepository_GetByCardToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSavedCardRepository_GetByCardToken_Call) RunAndReturn(run func(context.Context, string) (payment.SavedCard, error)) *MockSavedCardRepository_GetByCardToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockSavedCardRepository) GetByID(ctx context.Context, id string) (payment.SavedCard, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 payment.SavedCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (payment.SavedCard, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) payment.SavedCard); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(payment.SavedCard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSavedCardRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSavedCardRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSavedCardRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSavedCardRepository_GetByID_Call {
	return &MockSavedCardRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSavedCardRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockSavedCardRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSavedCardRepository_GetByID_Call) Return(_a0 payment.SavedCard, _a1 error) *MockSavedCardRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSavedCardRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (payment.SavedCard, error)) *MockSavedCardRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultCard provides a mock function with given fields: ctx, memberID
func (_m *MockSavedCardRepository) GetDefaultCard(ctx context.Context, memberID string) (payment.SavedCard, error) {
	ret := _m.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultCard")
	}

	var r0 payment.SavedCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (payment.SavedCard, error)); ok {
		return rf(ctx, memberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) payment.SavedCard); ok {
		r0 = rf(ctx, memberID)
	} else {
		r0 = ret.Get(0).(payment.SavedCard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSavedCardRepository_GetDefaultCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultCard'
type MockSavedCardRepository_GetDefaultCard_Call struct {
	*mock.Call
}

// GetDefaultCard is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockSavedCardRepository_Expecter) GetDefaultCard(ctx interface{}, memberID interface{}) *MockSavedCardRepository_GetDefaultCard_Call {
	return &MockSavedCardRepository_GetDefaultCard_Call{Call: _e.mock.On("GetDefaultCard", ctx, memberID)}
}

func (_c *MockSavedCardRepository_GetDefaultCard_Call) Run(run func(ctx context.Context, memberID string)) *MockSavedCardRepository_GetDefaultCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSavedCardRepository_GetDefaultCard_Call) Return(_a0 payment.SavedCard, _a1 error) *MockSavedCardRepository_GetDefaultCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSavedCardRepository_GetDefaultCard_Call) RunAndReturn(run func(context.Context, string) (payment.SavedCard, error)) *MockSavedCardRepository_GetDefaultCard_Call {
	_c.Call.Return(run)
	return _c
}

// ListByMemberID provides a mock function with given fields: ctx, memberID
func (_m *MockSavedCardRepository) ListByMemberID(ctx context.Context, memberID string) ([]payment.SavedCard, error) {
	ret := _m.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for ListByMemberID")
	}

	var r0 []payment.SavedCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]payment.SavedCard, error)); ok {
		return rf(ctx, memberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []payment.SavedCard); ok {
		r0 = rf(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.SavedCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSavedCardRepository_ListByMemberID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByMemberID'
type MockSavedCardRepository_ListByMemberID_Call struct {
	*mock.Call
}

// ListByMemberID is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockSavedCardRepository_Expecter) ListByMemberID(ctx interface{}, memberID interface{}) *MockSavedCardRepository_ListByMemberID_Call {
	return &MockSavedCardRepository_ListByMemberID_Call{Call: _e.mock.On("ListByMemberID", ctx, memberID)}
}

func (_c *MockSavedCardRepository_ListByMemberID_Call) Run(run func(ctx context.Context, memberID string)) *MockSavedCardRepository_ListByMemberID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSavedCardRepository_ListByMemberID_Call) Return(_a0 []payment.SavedCard, _a1 error) *MockSavedCardRepository_ListByMemberID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSavedCardRepository_ListByMemberID_Call) RunAndReturn(run func(context.Context, string) ([]payment.SavedCard, error)) *MockSavedCardRepository_ListByMemberID_Call {
	_c.Call.Return(run)
	return _c
}

// SetAsDefault provides a mock function with given fields: ctx, memberID, cardID
func (_m *MockSavedCardRepository) SetAsDefault(ctx context.Context, memberID string, cardID string) error {
	ret := _m.Called(ctx, memberID, cardID)

	if len(ret) == 0 {
		panic("no return value specified for SetAsDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, memberID, cardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSavedCardRepository_SetAsDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAsDefault'
type MockSavedCardRepository_SetAsDefault_Call struct {
	*mock.Call
}

// SetAsDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
//   - cardID string
func (_e *MockSavedCardRepository_Expecter) SetAsDefault(ctx interface{}, memberID interface{}, cardID interface{}) *MockSavedCardRepository_SetAsDefault_Call {
	return &MockSavedCardRepository_SetAsDefault_Call{Call: _e.mock.On("SetAsDefault", ctx, memberID, cardID)}
}

func (_c *MockSavedCardRepository_SetAsDefault_Call) Run(run func(ctx context.Context, memberID string, cardID string)) *MockSavedCardRepository_SetAsDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSavedCardRepository_SetAsDefault_Call) Return(_a0 error) *MockSavedCardRepository_SetAsDefault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSavedCardRepository_SetAsDefault_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSavedCardRepository_SetAsDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, card
func (_m *MockSavedCardRepository) Update(ctx context.Context, id string, card payment.SavedCard) error {
	ret := _m.Called(ctx, id, card)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, payment.SavedCard) error); ok {
		r0 = rf(ctx, id, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSavedCardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSavedCardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - card payment.SavedCard
func (_e *MockSavedCardRepository_Expecter) Update(ctx interface{}, id interface{}, card interface{}) *MockSavedCardRepository_Update_Call {
	return &MockSavedCardRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, card)}
}

func (_c *MockSavedCardRepository_Update_Call) Run(run func(ctx context.Context, id string, card payment.SavedCard)) *MockSavedCardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(payment.SavedCard))
	})
	return _c
}

func (_c *MockSavedCardRepository_Update_Call) Return(_a0 error) *MockSavedCardRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSavedCardRepository_Update_Call) RunAndReturn(run func(context.Context, string, payment.SavedCard) error) *MockSavedCardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSavedCardRepository creates a new instance of MockSavedCardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSavedCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSavedCardRepository {
	mock := &MockSavedCardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
