package domain

import (
	"time"
)

// Role represents the role of a member in the system.
//
// TYPE DESIGN:
//   - Custom string type for type safety (prevents passing arbitrary strings)
//   - Stored as TEXT in PostgreSQL, string in MongoDB
//   - Extensible: can add new roles (e.g., RoleLibrarian) without schema changes
type Role string

const (
	// RoleUser is a regular member who can borrow books.
	// Default role assigned to all new registrations.
	// Permissions: borrow books, create reservations, view own profile.
	RoleUser Role = "user"

	// RoleAdmin has full access to manage the library.
	// Permissions: all user permissions + manage books, authors, members.
	// Manually assigned (not available via public registration).
	RoleAdmin Role = "admin"
)

// Member represents a member entity in the library system.
//
// TYPE HIERARCHY:
//   - This is a DOMAIN ENTITY (pure business object)
//   - Has NO external dependencies (authentication logic in infrastructure layer)
//   - Contains sensitive data (PasswordHash, Email) - NEVER expose in DTOs
//
// FIELD DESIGN DECISIONS:
//
// 1. ID, Email, PasswordHash, Role (NOT pointers):
//   - Required fields, never null in database
//   - ID: UUID v4 format
//   - Email: unique constraint enforced at database level
//   - PasswordHash: bcrypt hash (60 characters), NEVER the plain password
//   - Role: defaults to RoleUser
//
// 2. FullName (*string, pointer):
//   - Nullable: allows registration without providing full name
//   - Pointer enables UPDATE logic (nil = don't change, value = update)
//
// 3. Books ([]string, NOT pointer):
//   - List of borrowed book IDs
//   - Empty slice = member has no borrowed books (valid state)
//   - Denormalized for performance (avoid JOIN on every member query)
//
// 4. CreatedAt, UpdatedAt (time.Time, NOT pointer):
//   - Audit timestamps, always required
//   - Auto-populated by New() constructor or database triggers
//   - UpdatedAt modified on every UPDATE operation
//
// 5. LastLoginAt (*time.Time, pointer):
//   - Nullable: nil before first login
//   - Updated by UpdateLastLogin() method
//   - Used for analytics and security (detect stale accounts)
//
// SECURITY CONSIDERATIONS:
//   - PasswordHash: NEVER expose via API (excluded from Member.ToDTO())
//   - Email: Personally Identifiable Information (PII), handle carefully
//   - NOT cached (sensitive data, frequently updated)
//
// RELATIONSHIPS:
//   - Books: One-to-Many with Book entity (member borrows multiple books)
//   - Reservations: One-to-Many with Reservation entity (via member_id)
//   - Payments: One-to-Many with Payment entity (via member_id)
//
// BUSINESS RULES:
//   - Implemented in member.Service, NOT in entity
//   - Subscription pricing logic
//   - Borrowing limits
type Member struct {
	// ID is the unique identifier for the member (UUID v4 format).
	// Required, immutable after creation.
	ID string `db:"id" bson:"_id"`

	// Email is the unique email address used for authentication.
	// Required, unique constraint enforced at database level.
	// Used as username for login.
	Email string `db:"email" bson:"email"`

	// PasswordHash is the bcrypt hash of the member's password.
	// Required, generated by infrastructure/auth.PasswordService.Hash().
	// NEVER store or transmit plain passwords.
	// Minimum cost factor: 10 (configurable for production).
	PasswordHash string `db:"password_hash" bson:"password_hash"`

	// FullName is the complete name of the member (e.g., "John Doe").
	// Nullable: member can register without providing full name.
	// Displayed in UI, used for receipts and communications.
	FullName *string `db:"full_name" bson:"full_name"`

	// Role defines the member's access level and permissions.
	// Required, defaults to RoleUser on registration.
	// RoleAdmin grants full system access (manually assigned).
	Role Role `db:"role" bson:"role"`

	// Books is the list of book UUIDs currently borrowed by this member.
	// Empty slice = no borrowed books.
	// Updated when books are borrowed/returned.
	// Denormalized for read performance (avoids JOIN queries).
	Books []string `db:"books" bson:"books"`

	// CreatedAt is the timestamp when the member account was created.
	// Auto-populated by New() constructor.
	// Immutable, used for analytics and reporting.
	CreatedAt time.Time `db:"created_at" bson:"created_at"`

	// UpdatedAt is the timestamp when the member was last updated.
	// Auto-populated on creation, updated on every modification.
	// Used for optimistic locking and audit trails.
	UpdatedAt time.Time `db:"updated_at" bson:"updated_at"`

	// LastLoginAt is the timestamp of the member's most recent login.
	// Nullable: nil until first successful login.
	// Updated by memberops.LoginUseCase via UpdateLastLogin().
	// Used for security monitoring and inactive account detection.
	LastLoginAt *time.Time `db:"last_login_at" bson:"last_login_at"`
}

// New creates a new Member instance.
func New(req Request) Member {
	now := time.Now()
	return Member{
		Email:     req.Email,
		FullName:  &req.FullName,
		Role:      RoleUser, // Default role
		Books:     req.Books,
		CreatedAt: now,
		UpdatedAt: now,
	}
}
