### List of authors from the store
GET http://localhost/api/v1/authors
Content-Type: application/json
Authorization: Bearer {{authorization}}

### Add a new author to the store
POST http://localhost/api/v1/authors
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "fullName": "Zhanat Rakhmet",
  "pseudonym": "Bugielektrik",
  "specialty": "Gopher"
}

### Read the author from the store
GET http://localhost/api/v1/authors/1
Content-Type: application/json
Authorization: Bearer {{authorization}}

### Update the author in the store
PUT http://localhost/api/v1/authors/1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "fullName": "Zhanat Rakhmet",
  "pseudonym": "bugielektrik",
  "specialty": "gopher"
}

### Delete the author from the store
DELETE http://localhost/api/v1/authors/1
Content-Type: application/json
Authorization: Bearer {{authorization}}
