### List of authors from the store
GET http://localhost/api/v1/authors

### Add a new author to the store
POST http://localhost/api/v1/authors
Content-Type: application/json

{
  "fullName": "fullName",
  "pseudonym": "pseudonym",
  "specialty": "specialty"
}

### Read the author from the store
GET http://localhost/api/v1/authors/1

### Update the author in the store
PUT http://localhost/api/v1/authors/1
Content-Type: application/json

{
  "fullName": "fullName",
  "pseudonym": "pseudonym",
  "specialty": "specialty"
}

### Delete the author from the store
DELETE http://localhost/api/v1/authors/1