### Generate Token using clientID & secret
POST http://localhost/auth
Host: localhost
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=abcdef&client_secret=12345

> {% client.global.set("authorization", response.body.access_token); %}
