### List of books from the store
GET http://localhost/api/v1/books

### Add a new book to the store
POST http://localhost/api/v1/books
Content-Type: application/json

{
    "name": "name",
    "genre": "genre",
    "isbn": "isbn",
    "authors": [
        "1",
        "2"
    ]
}

### Read the book from the store
GET http://localhost/api/v1/books/1

### Update the book in the store
PUT http://localhost/api/v1/books/1
Content-Type: application/json

{
    "name": "name",
    "genre": "genre",
    "isbn": "isbn",
    "authors": [
        "1",
        "2"
    ]
}

### Delete the book from the store
DELETE http://localhost/api/v1/books/1